### ISSUE TITLE
Does it work on iOS?

### ISSUE THREAD

**Issue by sharpordie** [flyfishxu/Kadb#1]
The README talks about Kotlin Multiplatform and Android, but nothing about iOS. Is it supposed to work with iOS?

Thanks!

**Comment by flyfishxu** [comment]
Sorry, it doesn't support iOS Platform currently, now Kadb support Desktop(JVM Based) and Android. We are still working and hope to support iOS Platform in the future!

**Comment by flyfishxu** [comment]
Sorry, it doesn't support iOS Platform currently, now Kadb support Desktop(JVM Based) and Android. We are still working and hope to support iOS Platform in the future!

**Comment by sharpordie** [comment]
No need to apologize, it's a huge job! For those who would like to use ADB on iOS, the only thing available that works is [adb-mobile](https://github.com/wsvn53/adb-mobile).

**Comment by Flyfish233** [comment]
Currently no stable `Socket` support for Kotlin Native:

> Note that Okio doesn't yet support sockets on Kotlin/Native or Kotlin/JS.

> TLS is not supported on Kotlin/Native. (Ktor)

To support Darwin, native code is required. Therefore, adb binary is now the best choice.
