### ISSUE TITLE
How to maintain the connection?

### ISSUE THREAD

**Issue by olankens** [flyfishxu/Kadb#6]
Each time I relaunch my application, I have to authorize!

![](https://github.com/user-attachments/assets/ad79e4c8-6401-444f-91a4-6a00f82a802f)

How to prevent this?
Is there a way to keep using the same rsa key fingerprint?

**Comment by flyfishxu** [comment]
You need to initialize KadbCert in ApplicationInit, generate a new KadbCert by `KadbCert.get()`, and save it in your ways like File or SharedPreferences etc, then set the KadbCert by `KadbCert.set(cert.toByteArray(), key.toByteArray())`.
Here's the sample code to generate a new KadbCert and save it by SharedPreferences in Application:
```
// Try to get cert and key from SharedPreferences
val sp = applicationContext.getSharedPreferences("kadb", Context.MODE_PRIVATE)  
val cert = sp.getString("cert", null) 
val key = sp.getString("key", null) 
if (cert.isNullOrEmpty() || key.isNullOrEmpty()) { 
    // If KadbCert haven't been saved in SharedPreferences, generate a new one
    val pair = KadbCert.get()
    sp.edit()
        .putString("cert", pair.first.decodeToString())
        .putString("key", pair.second.decodeToString()).apply()
    return
}
try {
    KadbCert.set(cert.toByteArray(), key.toByteArray())
} catch (e: Exception) {
    if (e is CertificateExpiredException || e is CertificateNotYetValidException) {
    val pair = KadbCert.get()
    sp.edit().putString("cert", pair.first.decodeToString())
        .putString("key", pair.second.decodeToString()).apply()
    }
    throw e
}
```

**Comment by Flyfish233** [comment]
https://github.com/flyfishxu/Kadb/blob/main/docs/kadbcert.md
